const data = {
  products: [
    {
      name: 'condo1',
      slug: 'condo-1',
      category: 'Condo',
      image: '/images/condo1.png',
      price: 5000,
      brand: 'D Condo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'The best condo nearest by TU',
    },

    {
      name: 'home1',
      slug: 'home-1',
      category: 'Home',
      image: '/images/home1.png',
      price: 5000,
      brand: 'D Condo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'The best condo nearest by TU',
    },

    {
      name: 'Land 1',
      slug: 'land-1',
      category: 'Land',
      image: '/images/land1.png',
      price: 5000,
      brand: 'D Condo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'The best condo nearest by TU',
    },

    {
      name: 'Townhome1',
      slug: 'townhome-1',
      category: 'Townhome',
      image: '/images/townhome1.png',
      price: 5000,
      brand: 'D Condo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'The best condo nearest by TU',
    },

    {
      name: 'condo5',
      slug: 'condo-5',
      category: 'condo',
      image: '/images/condo5.png',
      price: 5000,
      brand: 'Kave Condo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'The best condo nearest by TU',
    },
    {
      name: 'condo6',
      slug: 'condo-6',
      category: 'condo',
      image: '/images/condo6.png',
      price: 5000,
      brand: 'Kave Condo',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'The best condo nearest by TU',
    },
  ],
};
export default data;
